### ISSUE TITLE
Market.trade_goods not loading properly

### ISSUE THREAD

**Issue by dasevilla** [marcoceppi/python-spacetraders#4]
The `trade_goods` field on `spacetraders.models.market.Market` doesn't load properly. The JSON field is `tradeGoods`.

Manually patching the file to the following seems to fix it:

```
trade_goods: Union[Unset, List["MarketTradeGood"]] = Field(alias="tradeGoods")
```

**Comment by marcoceppi** [comment]
Thanks for the report. It looks like for Optional parameters the API generator is using this magic UNSET definition which is skipping the code I added for pydantic Fields. I'll patch this up and have a release out later today
